### ISSUE TITLE
Wireframe de baja fidelidad

### ISSUE THREAD

**Issue by spozap** [spozap/TimeApp#1]
No puedo continuar con el wireframe ya que en la página actual solo deja crear 3 vistas.

https://www.mockflow.com/

**Comment by cf17josetorres** [comment]
sergi, esta pagina deja crear varias vistas he estado mirando va super bien. :)
https://app.moqups.com/

**Comment by spozap** [comment]
Wireframe terminado usando Moqups. Cierro incidencia
