### ISSUE TITLE
Crear layout para login

### ISSUE THREAD

**Issue by cf17josetorres** [spozap/TimeApp#2]
Estava con el fragment login y me a ocurrido un problema que añadir un elemento se descuadro todo,  y no funcionava si le daba al control z :)

**Comment by spozap** [comment]
Buenas Jose , lo he estado mirando y en principio ya no me da ningún error ni nada a mí , lo veo todo OK.

**Comment by cf17josetorres** [comment]
Ya esta terminado el fragment de login!
